[package]
name = "rexl"
version = "0.0.3"
authors = ["tuke <tukeof@gmail.com>"]
edition = "2018"
description = """
A simple algorithm library for Rust
"""
documentation = "https://github.com/bobbystrange/rexl/blob/master/README.md"
readme = "README.md"
homepage = "https://github.com/bobbystrange/rexl"
repository = "https://github.com/bobbystrange/rexl"
license = "GPL-2.0-or-later"
keywords = ["algorithms", "expression", "argparser", "timeit", "interpolation"]
categories = ["mathematics", "algorithms"]