[package]
name = "rexl"
version = "0.0.3"
authors = ["tuke <bobby.j.strange@gmail.com>"]
edition = "2018"
description = """
A simple algorithm library for Rust
"""
documentation = "https://github.com/bobbystrange/rexl/blob/master/rexl/README.md"
readme = "README.md"
homepage = "https://github.com/bobbystrange/rexl/tree/master/rexl"
repository = "https://github.com/bobbystrange/rexl/tree/master/rexl"
license = "MIT OR Apache-2.0"
keywords = ["algorithms", "expression", "argparser", "timeit", "interpolation"]
categories = ["mathematics", "algorithms"]